my_project_1:
  outputs:
    dev:
      account: "${{ secrets.SNOW_ACCOUNT }}"
      database: "${{ secrets.SNOW_DATABASE }}"
      password: "${{ secrets.SNOW_PASSWORD }}"
      role: "${{ secrets.SNOW_ROLE }}"
      schema: "${{ secrets.SNOW_SCHEMA }}"
      threads: 4
      type: snowflake
      user: "${{ secrets.SNOW_USER }}"
      warehouse: "${{ secrets.SNOW_WAREHOUSE }}"
  target: dev