my_project_1:
  outputs:
    dev:
      account: {{ account }}
      database: "DEMO_DB"
      password: "AbcdAbcdAbcd067$"
      role: "ACCOUNTADMIN"
      schema: "PUBLIC"
      threads: 4
      type: snowflake
      user: "pradeep"
      warehouse: "COMPUTE_WH"
  target: dev