my_project_1:
  outputs:
    dev:
      account: "{{account}}"
      database: "{{database}}"
      password: "{{password}}"
      role: "ACCOUNTADMIN"
      schema: "{{schema}}"
      threads: 4
      type: snowflake
      user: "{{user}}"
      warehouse: "{{warehouse}}"
  target: dev